/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package docencia;

import static docencia.FrmDocencia.tablaCursos;
import utilidades.ObjetosParaEditar;

/**
 *
 * @author cardo
 */
public class FrmEditarCursos extends javax.swing.JDialog {

    private ModeloCursosImpartidos modelo;
    private BDCursosImpartidos bd;
    private CursosImpartidos c;
    private CursosImpartidos curso;

    /**
     * Creates new form FrmEditarCursos
     */
    public FrmEditarCursos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        c = ObjetosParaEditar.c;
        this.setTitle("Editar curso");
        setCursoEditar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboCarreras = new javax.swing.JComboBox<>();
        cboAsignaturas = new javax.swing.JComboBox<>();
        spnSemestre = new javax.swing.JSpinner();
        cboCiclo = new javax.swing.JComboBox<>();
        spnHoras = new javax.swing.JSpinner();
        spnAlumnos = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 245, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel1.setText("Carrera: ");

        jLabel2.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel2.setText("Asignatura: ");

        jLabel3.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel3.setText("Semestre:");

        jLabel4.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel4.setText("Ciclo escolar:");

        jLabel5.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel5.setText("Horas por semana");

        jLabel6.setFont(new java.awt.Font("BodoniFLF", 1, 14)); // NOI18N
        jLabel6.setText("Alumnos Matriculados");

        cboCarreras.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        cboCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing.Computación", "Ing.Acuicultura", "Ing.Diseño", "Ing.Mecatronica", "Ing.Agricola", "Lic.Matematicas", "Lic.Zootecnia", " ", " " }));
        cboCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCarrerasActionPerformed(evt);
            }
        });

        cboAsignaturas.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        cboAsignaturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnSemestre.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        spnSemestre.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        cboCiclo.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        cboCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "V" }));

        spnHoras.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        spnHoras.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(50.0f), Float.valueOf(1.0f)));

        spnAlumnos.setFont(new java.awt.Font("BodoniFLF", 3, 14)); // NOI18N
        spnAlumnos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton2.setFont(new java.awt.Font("BodoniFLF", 1, 18)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(spnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboCarreras, 0, 190, Short.MAX_VALUE)
                                    .addComponent(cboAsignaturas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnHoras)
                                    .addComponent(spnSemestre)
                                    .addComponent(cboCiclo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cboAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(spnSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cboCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(spnHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCarrerasActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        editar();
        //txtCursoAModificar.setText(c.toString());
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEditarCursos dialog = new FrmEditarCursos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void editar() {

        String carrera = cboCarreras.getSelectedItem().toString();
        String asignatura = cboAsignaturas.getSelectedItem().toString();
        int semestre = (int) spnSemestre.getValue();
        String cicloEscolar = cboCiclo.getSelectedItem().toString();
        float horas = (float) spnHoras.getValue();
        int alumnos = (int) spnAlumnos.getValue();
        curso = new CursosImpartidos(new Carrera(carrera), new Asignatura(asignatura), semestre, cicloEscolar, horas, alumnos);
    }

    public CursosImpartidos getCurso() {
        return curso;
    }
    public void setCursoEditar(){
        cboCarreras.setSelectedItem(c.getCarrera().getNombreCarrera());
        cboAsignaturas.setSelectedItem(c.getAsignatura().getNombre());
        spnSemestre.setValue(c.getSemestre());
        cboCiclo.setSelectedItem(c.getCicloEscolar());
        spnHoras.setValue(c.getHoras());
        spnAlumnos.setValue(c.getNumAlumnos());
        //cboCarreras.add(c.getCarrera());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAsignaturas;
    private javax.swing.JComboBox<String> cboCarreras;
    private javax.swing.JComboBox<String> cboCiclo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner spnAlumnos;
    private javax.swing.JSpinner spnHoras;
    private javax.swing.JSpinner spnSemestre;
    // End of variables declaration//GEN-END:variables
}
