/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ResumenActividades;

import java.util.LinkedList;

/**
 *
 * @author Adrian Rubio
 * rubioalvaradoadrian@gmail.com
 */
public class GestionActividadess extends javax.swing.JDialog {
    private ListaDeActividades a;
    private boolean situacion;
    /**
     * Creates new form GestionActividadess
     */
    public GestionActividadess(java.awt.Frame parent, boolean modal,ListaDeActividades a) {
        super(parent, modal);
        initComponents();
        this.a=a;
        situacionBase();
        situacion=false;
        llenarActividades();
        this.txtActividades.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtActividades = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblActividad = new javax.swing.JLabel();
        txtActividad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Actividades"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtActividades.setColumns(20);
        txtActividades.setRows(5);
        jScrollPane1.setViewportView(txtActividades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 23, 270, 290));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActividad.setText("Actividad");
        jPanel2.add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));
        jPanel2.add(txtActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, -1));

        jLabel2.setText("Indice:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));
        jPanel2.add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, 30));

        btnAgregar.setText("+");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 40));

        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 80, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, -1));

        btnEliminar.setText("-");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 34, 234, 280));

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        double indice=Double.parseDouble(this.txtIndice.getText());
        for(Actividad a1:a.getListaDeActividades()){
            if(a1.getIndice()==indice){
                this.lblActividad.setVisible(true);
                this.txtActividad.setVisible(true);
                this.txtActividad.setText(a1.getActividad());

                this.btnEliminar.setVisible(true);
                break;
            }
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        this.txtIndice.setText("");
        this.txtActividad.setText("");
        this.btnAgregar.setVisible(false);
        this.btnBuscar.setVisible(false);
        this.txtActividad.setVisible(true);
        this.lblActividad.setVisible(true);
        this.btnCancelar.setVisible(true);
        this.btnAceptar.setVisible(true);
        this.situacion=false;
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        situacionBase();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        if(!situacion){
            this.a.agregarActividad(new Actividad(Double.parseDouble(this.txtIndice.getText()),this.txtActividad.getText()));
            
        }else{
            a.eliminarActividad(Double.parseDouble(this.txtIndice.getText()));
        }
        situacion=false;
        llenarActividades();
        situacionBase();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        this.btnCancelar.setVisible(true);
        this.btnAceptar.setVisible(true);    
        this.btnEliminar.setVisible(false);
        this.txtIndice.setEditable(false);
        this.txtActividad.setEditable(false);
        this.btnAgregar.setVisible(false);
        this.btnBuscar.setVisible(false);
        this.txtActividad.setVisible(true);
        this.lblActividad.setVisible(true);
        situacion=true;
            
            
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionActividadess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionActividadess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionActividadess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionActividadess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionActividadess dialog = new GestionActividadess(new javax.swing.JFrame(), true,new ListaDeActividades());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextArea txtActividades;
    private javax.swing.JTextField txtIndice;
    // End of variables declaration//GEN-END:variables
     private void situacionBase(){
        this.btnAceptar.setVisible(false);
        this.btnCancelar.setVisible(false);
        this.btnEliminar.setVisible(false);
        this.txtActividad.setVisible(false);
        this.lblActividad.setVisible(false);
        this.txtIndice.setEditable(true);
        this.btnBuscar.setVisible(true);
        this.txtIndice.setText("");
        this.btnAgregar.setVisible(true);
    }
     private void llenarActividades(){
         this.txtActividades.setText("");
         for(Actividad a1 : a.getListaDeActividades()){
             this.txtActividades.setText(this.txtActividades.getText()+a1.getIndice()+":"+a1.getActividad()+"\n");
         }
     }
     public ListaDeActividades regresarActividades(){
         return a;
     }

}
